// <auto-generated />
using System;
using FitByBitService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitByBitApiService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240418231510_Creating Meal Plan")]
    partial class CreatingMealPlan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FitByBitApiService.Entities.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("643ace07-77ea-4124-abcc-87fd78291095"),
                            ExerciseName = "Forward Lunge",
                            Name = "20 Minute HIIT Workout",
                            Number = "1",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("377252af-2a20-4a4b-bca9-e60dc1fc3ead"),
                            ExerciseName = "Bodyweight Squat",
                            Name = "20 Minute HIIT Workout",
                            Number = "2",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("114cfd16-2475-4d60-90da-acbd8c42e325"),
                            ExerciseName = "Mountain Climber",
                            Name = "20 Minute HIIT Workout",
                            Number = "3",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("349db653-afee-4cc7-88d4-97addf54f360"),
                            ExerciseName = "Jogging in Place",
                            Name = "20 Minute HIIT Workout",
                            Number = "4",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("294acad5-92c3-4311-b9b8-e7fafe8f16f4"),
                            ExerciseName = "Burpees",
                            Name = "20 Minute HIIT Workout",
                            Number = "5",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("458253d0-a946-4523-99ba-69687bb150e3"),
                            ExerciseName = "High Kick",
                            Name = "20 Minute HIIT Workout",
                            Number = "6",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("caf81213-7de5-4138-a6d4-4f89c2ec208b"),
                            ExerciseName = "Jumping Jacks",
                            Name = "30 Minute Cardio Workout",
                            Number = "1",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("6dcee431-f991-4926-9d0e-586110d0a317"),
                            ExerciseName = "Push Ups",
                            Name = "30 Minute Cardio Workout",
                            Number = "2",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("811872f8-c80b-4b2b-8750-eb1b133ea465"),
                            ExerciseName = "Crunches",
                            Name = "30 Minute Cardio Workout",
                            Number = "3",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("4b9abcb5-8d5d-430f-a1a2-f8c0e18bdb68"),
                            ExerciseName = "Squat Jumps",
                            Name = "30 Minute Cardio Workout",
                            Number = "4",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("55d819a4-b78a-4e46-81c7-41f67576ae95"),
                            ExerciseName = "Mountain Climber",
                            Name = "30 Minute Cardio Workout",
                            Number = "5",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("b0dff1f3-367e-4284-8257-2d2fcc73d798"),
                            ExerciseName = "Burpees",
                            Name = "30 Minute Cardio Workout",
                            Number = "6",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("2995fc77-43cd-459c-a3a4-d94a0afffff2"),
                            ExerciseName = "Jogging in Place",
                            Name = "30 Minute Cardio Workout",
                            Number = "7",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("33d3992c-e74f-4c31-8e49-742571b09589"),
                            ExerciseName = "Jumping Lunges",
                            Name = "30 Minute Cardio Workout",
                            Number = "8",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("5af11fd7-7cd1-4ff8-be7c-fe5413dc6f37"),
                            ExerciseName = "Burpees",
                            Name = "45 Minute HIIT Workout",
                            Number = "1",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("86c1117e-1a01-4782-ad92-e826406b8306"),
                            ExerciseName = "Squat Jumps",
                            Name = "45 Minute HIIT Workout",
                            Number = "2",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("0c9bb45f-e041-448f-912c-4df9a4252406"),
                            ExerciseName = "Crunches",
                            Name = "45 Minute HIIT Workout",
                            Number = "3",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("b68b7e41-efd6-4e96-850c-1d3c8c3fb724"),
                            ExerciseName = "Jumping Jacks",
                            Name = "45 Minute HIIT Workout",
                            Number = "4",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("1c4d5b36-dfee-426b-93db-f3920e6144e4"),
                            ExerciseName = "Jumping Lunges",
                            Name = "45 Minute HIIT Workout",
                            Number = "5",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("6fbc2f4e-cc0e-4945-9a34-6e194c04e351"),
                            ExerciseName = "Push Ups",
                            Name = "45 Minute HIIT Workout",
                            Number = "6",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("4255eca0-a063-4b41-a40e-9508393adf2c"),
                            ExerciseName = "Deadlift",
                            Name = "Beginner Strength Training Workout",
                            Number = "1",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("10570e57-7a5d-4b2d-9e55-4a6e58f533c5"),
                            ExerciseName = "Leg Press",
                            Name = "Beginner Strength Training Workout",
                            Number = "2",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("b725faad-b1e9-43a1-bdaf-bd4412d44943"),
                            ExerciseName = "Walking Lunge",
                            Name = "Beginner Strength Training Workout",
                            Number = "3",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("0e69c619-55ef-4649-920c-988283eef19a"),
                            ExerciseName = "Cruches",
                            Name = "Beginner Strength Training Workout",
                            Number = "4",
                            Reps = "12, 12, 12",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("496a3cb5-77a2-4c45-8c45-b48a703ff00e"),
                            ExerciseName = "Lateral Raise",
                            Name = "Beginner Strength Training Workout",
                            Number = "5",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("d23f337e-a18a-431b-811d-0f9b59e54fb5"),
                            ExerciseName = "Hammer Dumbbell Curl",
                            Name = "Beginner Strength Training Workout",
                            Number = "6",
                            Reps = "12, 10, 9",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("1d452151-9dab-4d63-a92d-4aea933da97b"),
                            ExerciseName = "Goblet Squat",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "1",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("22fad580-0e79-4046-af0b-7fbd73da4d7e"),
                            ExerciseName = "Stiff Leg Deadlift",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "2",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("e800c61c-42c9-4803-9c17-9508855286c4"),
                            ExerciseName = "Leg Press",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "3",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("51a7feea-d909-42dc-9e9f-037c423a85fe"),
                            ExerciseName = "Walking Lunge",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "4",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("fecd7b1e-dbc4-4bf1-91ab-ea93c0af77cb"),
                            ExerciseName = "Seated Calf Raise",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "5",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("555a4d9b-a3bc-436b-9fbc-9fc2b8d05c05"),
                            ExerciseName = "Crunches",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "6",
                            Reps = "12, 12, 12",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("05684fca-ab99-4ae5-bc60-32bc6691a55d"),
                            ExerciseName = "Lateral Raise",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "7",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("eeff1dd9-9ae4-4f54-b775-ebf4787ad933"),
                            ExerciseName = "Hammer Dumbbell Curl",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "8",
                            Reps = "12, 10, 9",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("141b108c-0a54-412f-9eb8-1978371e5cf0"),
                            ExerciseName = "Straight Bar Tricep Extension",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "9",
                            Reps = "12, 10, 10",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("d380ed6a-1352-4ca5-ae69-2fe8b22dccfb"),
                            ExerciseName = "Burpee",
                            Name = "Beginner At Home Workout",
                            Number = "1",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("563cde1b-9f35-4998-b492-2c304b613e2d"),
                            ExerciseName = "Push Up",
                            Name = "Beginner At Home Workout",
                            Number = "2",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("73ecedee-3998-405f-bf28-bfd4b6a6bbe7"),
                            ExerciseName = "Floor Crunch",
                            Name = "Beginner At Home Workout",
                            Number = "3",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("a43affc9-3f17-4ca3-aa8d-e6c9f902e37d"),
                            ExerciseName = "Squat Jump",
                            Name = "Beginner At Home Workout",
                            Number = "4",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("690649ac-b655-48d2-82aa-8d017c0420e6"),
                            ExerciseName = "Bicycle Crunch",
                            Name = "Beginner At Home Workout",
                            Number = "5",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("93a1096d-5563-4415-8633-71f27cd15fa5"),
                            ExerciseName = "Mountain Climber",
                            Name = "Beginner At Home Workout",
                            Number = "6",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("4dcd47cd-c41b-4870-a6a3-53e51851f537"),
                            ExerciseName = "Reverse or Walking Lunge",
                            Name = "Beginner At Home Workout",
                            Number = "7",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("5b3b1a4b-9c9f-4bea-976d-0092d65895c1"),
                            ExerciseName = "Star Jumps",
                            Name = "Beginner At Home Workout",
                            Number = "8",
                            Set = "2",
                            Time = "1 min"
                        });
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.WorkOutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkOutProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.WorkoutProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpertiseLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPrograms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7858ca5f-1e0a-4297-8448-913d2aab673e"),
                            Category = 1,
                            ExerciseName = "20 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("664c155f-a154-41af-88a2-d2ced8fff8f5"),
                            Category = 4,
                            ExerciseName = "20 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("c0835e29-3e22-4a8b-9309-22554d3f52f8"),
                            Category = 1,
                            ExerciseName = "30 Minute Cardio Workout",
                            ExpertiseLevel = 1
                        },
                        new
                        {
                            Id = new Guid("bf9b2ad7-08ab-4e69-be16-db3ddfdc81bb"),
                            Category = 1,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("8cd4ef29-5511-4db1-986e-95ceb9adfcb6"),
                            Category = 1,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("ad16aa80-c6ab-4386-b095-2feee689a779"),
                            Category = 2,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("e6456013-5b85-4a11-bf00-302c6aeeda8b"),
                            Category = 2,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("5cbf2b60-8934-4bf6-8ea4-006e3ee167d1"),
                            Category = 4,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("e487b881-f28b-4526-851c-853f915ae1fb"),
                            Category = 4,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("275ec172-ee2b-4aba-880a-fbd3c20fc1b1"),
                            Category = 3,
                            ExerciseName = "Beginner Strength Training Workout",
                            ExpertiseLevel = 1
                        },
                        new
                        {
                            Id = new Guid("ac30b975-fed7-4d8c-ba91-d1a2695c003f"),
                            Category = 1,
                            ExerciseName = "Intermediate Fat Loss Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("e5227d53-50de-4fcb-96d0-ae45db8b69e8"),
                            Category = 1,
                            ExerciseName = "Intermediate Fat Loss Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("97783f5d-814e-4067-b164-1935dd976084"),
                            Category = 4,
                            ExerciseName = "Intermediate Fat Loss Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("16c072ec-9f9b-49f7-a3b1-7ee0d08094c6"),
                            Category = 4,
                            ExerciseName = "Intermediate Fat Loss Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("e3d9ca0c-81ac-4929-96dc-12a7d227a541"),
                            Category = 1,
                            ExerciseName = "Beginner At Home Workout",
                            ExpertiseLevel = 1
                        });
                });

            modelBuilder.Entity("FitByBitService.Entities.Models.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Calories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce93f9f8-fbdb-4c25-b7df-887c8d1945e6"),
                            Calories = "130",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2525),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2528),
                            Name = "White Rice"
                        },
                        new
                        {
                            Id = new Guid("df47cc0d-0df6-4b15-8f32-e1e05950f757"),
                            Calories = "130",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2565),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2566),
                            Name = "Medium Grain White Rice"
                        },
                        new
                        {
                            Id = new Guid("ee0c3dcc-bac9-44e0-9510-61638cb18332"),
                            Calories = "108",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2568),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2569),
                            Name = "Rice Noodles (Cooked)"
                        },
                        new
                        {
                            Id = new Guid("f6a14dbe-fb66-4a16-aec3-1105ee3d11be"),
                            Calories = "123",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2571),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2571),
                            Name = "Brown Rice"
                        },
                        new
                        {
                            Id = new Guid("78b0ef47-6e55-4289-847a-c2aadb17edc3"),
                            Calories = "145",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2573),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2573),
                            Name = "Beef And Rice No Sauce"
                        },
                        new
                        {
                            Id = new Guid("312e22b1-c5c2-4370-821d-ab0ec22a82c7"),
                            Calories = "136",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2578),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2578),
                            Name = "Beef And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("665056a4-fb64-409f-a714-0a208ec37c45"),
                            Calories = "112",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2580),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2580),
                            Name = "Chili Con Carne With Beans And Rice"
                        },
                        new
                        {
                            Id = new Guid("601233d1-8969-48e5-9ae1-3e4ea112b9fe"),
                            Calories = "139",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2582),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2583),
                            Name = "Pork And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("c7f57e54-1851-4545-a20f-37b63fabde1b"),
                            Calories = "148",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2594),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2595),
                            Name = "Chicken Or Turkey And Rice No Sauce"
                        },
                        new
                        {
                            Id = new Guid("79fa2d2f-9682-4e62-bfdf-7ecdebd3b3f5"),
                            Calories = "141",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2598),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2598),
                            Name = "Chicken Or Turkey And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("b53dc888-0afe-4c16-97ee-07e1f7a70742"),
                            Calories = "135",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2600),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2600),
                            Name = "Fish And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("6daef1cd-6cab-492a-83c9-1c81392918f7"),
                            Calories = "147",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2602),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2602),
                            Name = "Beef, Rice And Vegetables"
                        },
                        new
                        {
                            Id = new Guid("07258183-fd98-420d-8643-552bcbdc6045"),
                            Calories = "128",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2604),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2604),
                            Name = "Pork, Rice And Vegetables "
                        },
                        new
                        {
                            Id = new Guid("09cdaf6e-fe3b-4f55-9ba2-fe8ab69f2115"),
                            Calories = "381",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2605),
                            FoodGroup = "3",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2606),
                            Name = "Cereal (Kellogg's Rice Krispies)"
                        },
                        new
                        {
                            Id = new Guid("61457171-4cc3-48ac-9d1c-3c9f775cd4a7"),
                            Calories = "149",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2616),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2617),
                            Name = "Whole Wheat Pasta"
                        },
                        new
                        {
                            Id = new Guid("ebc5140b-8e6b-4712-8467-55fbaf80e905"),
                            Calories = "157",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2619),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2619),
                            Name = "Pasta Cooked"
                        },
                        new
                        {
                            Id = new Guid("44572c65-446d-45ad-8691-5b98a7ba30c4"),
                            Calories = "148",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2624),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2624),
                            Name = "Pasta Whole Grain Cooked"
                        },
                        new
                        {
                            Id = new Guid("e526e4e7-3411-46ba-8453-6581a0f03458"),
                            Calories = "192",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2627),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2627),
                            Name = "Chicken Breast Baked"
                        },
                        new
                        {
                            Id = new Guid("3da70869-17dd-4caa-bb77-60edff65c9c7"),
                            Calories = "176",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2629),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2629),
                            Name = "Chicken Breast Grilled"
                        },
                        new
                        {
                            Id = new Guid("2c0533c8-c9f8-4bca-9032-c35fa693e857"),
                            Calories = "226",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2631),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2631),
                            Name = "Chicken Leg Drumstick And Thigh Baked"
                        },
                        new
                        {
                            Id = new Guid("666c6f34-46c6-460f-9595-5314c6d6885f"),
                            Calories = "190",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2633),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2633),
                            Name = "Chicken Drumstick Baked"
                        },
                        new
                        {
                            Id = new Guid("a5694ada-5df8-4464-9fd1-39b3c5e87b66"),
                            Calories = "200",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2635),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2635),
                            Name = "Chicken Drumstick Grilled"
                        },
                        new
                        {
                            Id = new Guid("af546837-1b10-4392-8aa9-cde9eb27da98"),
                            Calories = "211",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2637),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2637),
                            Name = "Chicken Drumstick Fried"
                        },
                        new
                        {
                            Id = new Guid("ce32120f-b086-42bc-8a32-cfb87d2522c5"),
                            Calories = "182",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2639),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2639),
                            Name = "Wild Atlantic Salmon"
                        },
                        new
                        {
                            Id = new Guid("91f16815-1f04-4dd2-b3c1-a91c85fbb9c7"),
                            Calories = "117",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2643),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2643),
                            Name = "Smoked Salmon"
                        },
                        new
                        {
                            Id = new Guid("7ea841cf-f140-4573-aff4-ec9a288116e7"),
                            Calories = "167",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2646),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2646),
                            Name = "Canned Salmon"
                        },
                        new
                        {
                            Id = new Guid("6a7b988b-34f5-4f6d-8ee1-16b2e31934df"),
                            Calories = "136",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2648),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2648),
                            Name = "Canned Pink Salmon"
                        },
                        new
                        {
                            Id = new Guid("3b61431d-fb09-4f19-8fe1-bb136b026e20"),
                            Calories = "206",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2649),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2650),
                            Name = "Farmed Atlantic Salmon"
                        },
                        new
                        {
                            Id = new Guid("6d6713a2-7cfb-492f-a9ce-14ca1972db41"),
                            Calories = "183",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2651),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2652),
                            Name = "Salmon Baked"
                        },
                        new
                        {
                            Id = new Guid("ba46838f-ad25-4911-84f4-85fc84bc8bc6"),
                            Calories = "71",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2654),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2654),
                            Name = "Fortified Fruit Juice Smoothie"
                        },
                        new
                        {
                            Id = new Guid("4b37708d-ef97-409c-ba19-d8d72f3f3923"),
                            Calories = "52",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2657),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2657),
                            Name = "Apples"
                        },
                        new
                        {
                            Id = new Guid("6d700815-f0e4-485e-83e2-a9ba8e892ba8"),
                            Calories = "48",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2659),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2659),
                            Name = "Apples (Without Skin)"
                        },
                        new
                        {
                            Id = new Guid("77d0ccae-8397-4860-8ae9-bd390692b3ec"),
                            Calories = "89",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2664),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2664),
                            Name = "Bananas"
                        });
                });

            modelBuilder.Entity("FitByBitService.Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("Bmi")
                        .HasColumnType("float");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentFitness")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FitnessGoal")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StartingWeight")
                        .HasColumnType("float");

                    b.Property<double>("TargetWeight")
                        .HasColumnType("float");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8b93395f-3b0d-496e-bdaa-b1bf2c327ba0",
                            AccessFailedCount = 0,
                            Age = 23,
                            Bmi = 1.8899999999999999,
                            ConcurrencyStamp = "1f407faa-c1de-442e-a9ee-5460c694376c",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2776),
                            CurrentFitness = 1,
                            Email = "superuserD@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            FitnessGoal = 1,
                            Height = 1.8300000000000001,
                            IsActive = true,
                            IsDeleted = false,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2777),
                            NormalizedEmail = "SUPERUSERD@GMAIL.COM",
                            NormalizedUserName = "SUPERUSER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBz/C9ODZ+1wHcPt942B95p8FtlrYSZrtMiKWbrD2TPfLw78r84IPGNfgsuDxYi8Gg==",
                            PhoneNumber = "08130927418",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "886330e8-6eff-4626-8f34-868c2db4d845",
                            StartingWeight = 80.0,
                            TargetWeight = 0.0,
                            TwoFactorEnabled = false,
                            UserName = "superuser@gmail.com"
                        },
                        new
                        {
                            Id = "26abf175-ca22-4aac-824a-8368f8ed0f15",
                            AccessFailedCount = 0,
                            Age = 23,
                            Bmi = 1.8899999999999999,
                            ConcurrencyStamp = "7d265b03-261e-49a2-ab83-72d1bcd1c200",
                            CreatedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2840),
                            CurrentFitness = 1,
                            Email = "osinfadeidris@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Idris",
                            FitnessGoal = 1,
                            Height = 1.8300000000000001,
                            IsActive = true,
                            IsDeleted = false,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Osinfade",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 4, 18, 23, 15, 9, 850, DateTimeKind.Utc).AddTicks(2840),
                            NormalizedEmail = "OSINFADEIDRIS@GMAIL.COM",
                            NormalizedUserName = "OSINFADEIDRIS@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBz/C9ODZ+1wHcPt942B95p8FtlrYSZrtMiKWbrD2TPfLw78r84IPGNfgsuDxYi8Gg==",
                            PhoneNumber = "07069576909",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a547a5e0-d89f-4dcc-83b7-14277d0a4670",
                            StartingWeight = 80.0,
                            TargetWeight = 0.0,
                            TwoFactorEnabled = false,
                            UserName = "osinfadeidris@gmail.com"
                        });
                });

            modelBuilder.Entity("FitByBitService.Entities.Models.VerificationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("Expiry")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VerificationOtps");
                });

            modelBuilder.Entity("FitByBitService.Entities.Models.VerificationOtp", b =>
                {
                    b.HasOne("FitByBitService.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
