// <auto-generated />
using System;
using FitByBitApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitByBitApiService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240428161955_Updated workout plan datas")]
    partial class Updatedworkoutplandatas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FitByBitApiService.Entities.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f26f3540-fe6a-454f-9a77-219e58127866"),
                            ExerciseName = "Forward Lunge",
                            Name = "20 Minute HIIT Workout",
                            Number = "1",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("0c5eac8f-49a7-4de8-b61e-bbe1d3a92702"),
                            ExerciseName = "Bodyweight Squat",
                            Name = "20 Minute HIIT Workout",
                            Number = "2",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("4cb0881b-2d5c-4620-9932-e2c1eb4751fd"),
                            ExerciseName = "Mountain Climber",
                            Name = "20 Minute HIIT Workout",
                            Number = "3",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("af68b70e-f005-4f61-b260-8e56209a6027"),
                            ExerciseName = "Jogging in Place",
                            Name = "20 Minute HIIT Workout",
                            Number = "4",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("7d87e2d0-afba-4224-ab35-e2357e08235c"),
                            ExerciseName = "Burpees",
                            Name = "20 Minute HIIT Workout",
                            Number = "5",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("c49e0074-03b8-4897-b21c-a834cb7385dc"),
                            ExerciseName = "High Kick",
                            Name = "20 Minute HIIT Workout",
                            Number = "6",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("2d23de4a-c3a1-4a6c-aa18-af28c8bc48a8"),
                            ExerciseName = "Jumping Jacks",
                            Name = "30 Minute Cardio Workout",
                            Number = "1",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("287a8943-8b11-4d31-b175-e9497054791b"),
                            ExerciseName = "Push Ups",
                            Name = "30 Minute Cardio Workout",
                            Number = "2",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("a301f0b9-575a-4a41-a910-0a12b9570764"),
                            ExerciseName = "Crunches",
                            Name = "30 Minute Cardio Workout",
                            Number = "3",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("ffbe5779-d51f-4b6e-987e-e14aa4226016"),
                            ExerciseName = "Squat Jumps",
                            Name = "30 Minute Cardio Workout",
                            Number = "4",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("0b8cecb9-b627-4fef-8081-7bf474666c64"),
                            ExerciseName = "Mountain Climber",
                            Name = "30 Minute Cardio Workout",
                            Number = "5",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("9fa43cc8-d1c2-4432-9f2c-b0bf29feef55"),
                            ExerciseName = "Burpees",
                            Name = "30 Minute Cardio Workout",
                            Number = "6",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("2adc4d8f-34eb-4bc6-82c1-6e1ad0a94511"),
                            ExerciseName = "Jogging in Place",
                            Name = "30 Minute Cardio Workout",
                            Number = "7",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("9c650324-b213-4c65-9987-738de479b738"),
                            ExerciseName = "Jumping Lunges",
                            Name = "30 Minute Cardio Workout",
                            Number = "8",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("99d422e8-07c6-44b7-be5a-9d6478735020"),
                            ExerciseName = "Burpees",
                            Name = "45 Minute HIIT Workout",
                            Number = "1",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("c7b94869-9749-4758-b6a6-41aa1b19d1d0"),
                            ExerciseName = "Squat Jumps",
                            Name = "45 Minute HIIT Workout",
                            Number = "2",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("72515a5c-d49e-4cc3-8d69-fef2e7b692d4"),
                            ExerciseName = "Crunches",
                            Name = "45 Minute HIIT Workout",
                            Number = "3",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("a06a8296-715e-4fa9-b260-b9f035c72f57"),
                            ExerciseName = "Jumping Jacks",
                            Name = "45 Minute HIIT Workout",
                            Number = "4",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("311ba19d-a94d-4732-9137-8ebd7357273f"),
                            ExerciseName = "Jumping Lunges",
                            Name = "45 Minute HIIT Workout",
                            Number = "5",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("57259327-f9b2-4fee-9ad5-ac12c0af5628"),
                            ExerciseName = "Push Ups",
                            Name = "45 Minute HIIT Workout",
                            Number = "6",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("484de6df-ee7a-4a01-ac2b-5c5740584c2f"),
                            ExerciseName = "Deadlift",
                            Name = "Beginner Strength Training Workout",
                            Number = "1",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("58e84530-81b8-428a-a11d-641f2f2b3605"),
                            ExerciseName = "Leg Press",
                            Name = "Beginner Strength Training Workout",
                            Number = "2",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("789c0c1d-d744-4ede-a87d-a76d8594b186"),
                            ExerciseName = "Walking Lunge",
                            Name = "Beginner Strength Training Workout",
                            Number = "3",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("2fa36877-dfd8-4d54-98a8-aa20ebb236d7"),
                            ExerciseName = "Cruches",
                            Name = "Beginner Strength Training Workout",
                            Number = "4",
                            Reps = "12, 12, 12",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("57aad64f-8f7d-4622-a3c4-eb2aab8c7bed"),
                            ExerciseName = "Lateral Raise",
                            Name = "Beginner Strength Training Workout",
                            Number = "5",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("61354b76-eb6c-49b6-8d62-59635e049abd"),
                            ExerciseName = "Hammer Dumbbell Curl",
                            Name = "Beginner Strength Training Workout",
                            Number = "6",
                            Reps = "12, 10, 9",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("31f59e57-bbe1-413d-bc38-fe25aa842451"),
                            ExerciseName = "Goblet Squat",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "1",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("0d65ab4b-0e58-497f-978b-14763f120fbe"),
                            ExerciseName = "Stiff Leg Deadlift",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "2",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("50867182-242f-4343-a2b1-e5f1abdc9414"),
                            ExerciseName = "Leg Press",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "3",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("fda519dd-f560-4f01-8364-b8849f5e7447"),
                            ExerciseName = "Walking Lunge",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "4",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("fcf8201e-09c0-46f7-be4c-962d4336c6f6"),
                            ExerciseName = "Seated Calf Raise",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "5",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("b0637855-3f62-4134-9671-ab1fbc60b985"),
                            ExerciseName = "Crunches",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "6",
                            Reps = "12, 12, 12",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("f4ffcc12-7984-4ef1-a107-f93a483daacf"),
                            ExerciseName = "Lateral Raise",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "7",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("713c0ece-43fd-48bb-89f0-a2b62c6781d8"),
                            ExerciseName = "Hammer Dumbbell Curl",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "8",
                            Reps = "12, 10, 9",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("32f9adb7-e164-4616-adff-81185025fed3"),
                            ExerciseName = "Straight Bar Tricep Extension",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "9",
                            Reps = "12, 10, 10",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("73d8b813-c4a8-45b1-b332-08dc576c0188"),
                            ExerciseName = "Burpee",
                            Name = "Beginner At Home Workout",
                            Number = "1",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("94916b8d-cff3-4344-a2eb-98bb9b583217"),
                            ExerciseName = "Push Up",
                            Name = "Beginner At Home Workout",
                            Number = "2",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("8cf31599-2232-4133-86d7-961a2856e3d4"),
                            ExerciseName = "Floor Crunch",
                            Name = "Beginner At Home Workout",
                            Number = "3",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("96b3ba78-45fa-49c2-a025-a9f409e3381e"),
                            ExerciseName = "Squat Jump",
                            Name = "Beginner At Home Workout",
                            Number = "4",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("a69547e3-762f-4443-9bc2-b52106ae1101"),
                            ExerciseName = "Bicycle Crunch",
                            Name = "Beginner At Home Workout",
                            Number = "5",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("ae6c7346-2419-4a4c-988b-26d285f2c336"),
                            ExerciseName = "Mountain Climber",
                            Name = "Beginner At Home Workout",
                            Number = "6",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("0d680ef8-dc6b-41ab-a9ea-64063aead176"),
                            ExerciseName = "Reverse or Walking Lunge",
                            Name = "Beginner At Home Workout",
                            Number = "7",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("29b942db-bc86-4dae-b0c4-98f600ce5f7d"),
                            ExerciseName = "Star Jumps",
                            Name = "Beginner At Home Workout",
                            Number = "8",
                            Set = "2",
                            Time = "1 min"
                        });
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Calories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("706ce0d1-c27f-45e6-87a1-cd2ccc2110ff"),
                            Calories = "130",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(6476),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(6477),
                            Name = "White Rice"
                        },
                        new
                        {
                            Id = new Guid("bb6edc64-bcbb-49c9-9279-d410f10de644"),
                            Calories = "130",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8303),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8306),
                            Name = "Medium Grain White Rice"
                        },
                        new
                        {
                            Id = new Guid("3ac8bb61-8547-4744-8a40-28d2f28b8fa7"),
                            Calories = "108",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8313),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8314),
                            Name = "Rice Noodles (Cooked)"
                        },
                        new
                        {
                            Id = new Guid("0ac8a5e7-fabd-4e82-a236-91860428cac8"),
                            Calories = "123",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8319),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8320),
                            Name = "Brown Rice"
                        },
                        new
                        {
                            Id = new Guid("4860fee5-8690-4dcb-adf1-2438583867cf"),
                            Calories = "145",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8325),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8326),
                            Name = "Beef And Rice No Sauce"
                        },
                        new
                        {
                            Id = new Guid("fb245fbf-095a-450d-a22e-b908651b49bb"),
                            Calories = "136",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8342),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8343),
                            Name = "Beef And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("23681e01-7389-4fa4-b3d7-dfbd178a02b6"),
                            Calories = "112",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8364),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8365),
                            Name = "Chili Con Carne With Beans And Rice"
                        },
                        new
                        {
                            Id = new Guid("1c4d77f7-4eb6-4383-b8da-a71635dd0f72"),
                            Calories = "139",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8370),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8371),
                            Name = "Pork And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("d62736f0-2ce6-49c5-91a2-ffe43421cdc5"),
                            Calories = "148",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8376),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8377),
                            Name = "Chicken Or Turkey And Rice No Sauce"
                        },
                        new
                        {
                            Id = new Guid("802e6958-7020-4f96-88c5-600608cd02eb"),
                            Calories = "141",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8387),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8388),
                            Name = "Chicken Or Turkey And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("92a53578-81e2-4e5b-bcd0-753e42912de1"),
                            Calories = "135",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8394),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8395),
                            Name = "Fish And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("3fef63fe-d828-4ead-a2e3-5ae3aca6600f"),
                            Calories = "147",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8400),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8401),
                            Name = "Beef, Rice And Vegetables"
                        },
                        new
                        {
                            Id = new Guid("f2c3fee9-0bf6-485b-9f32-acc7257738dd"),
                            Calories = "128",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8406),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8408),
                            Name = "Pork, Rice And Vegetables "
                        },
                        new
                        {
                            Id = new Guid("6e52b36b-5c32-4ca1-a6c0-a811866af176"),
                            Calories = "381",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8413),
                            FoodGroup = "3",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8414),
                            Name = "Cereal (Kellogg's Rice Krispies)"
                        },
                        new
                        {
                            Id = new Guid("7dbf3977-d734-402d-a2c1-5b4410fd77a1"),
                            Calories = "149",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8426),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8427),
                            Name = "Whole Wheat Pasta"
                        },
                        new
                        {
                            Id = new Guid("0fbccb49-0761-4bec-87a2-011b26bee879"),
                            Calories = "157",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8432),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8433),
                            Name = "Pasta Cooked"
                        },
                        new
                        {
                            Id = new Guid("f1cb23b1-9a91-4d34-ae36-fc45a8212bff"),
                            Calories = "148",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8438),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8439),
                            Name = "Pasta Whole Grain Cooked"
                        },
                        new
                        {
                            Id = new Guid("1261f8e3-ecca-48e6-bc34-71b7a267945a"),
                            Calories = "192",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8448),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8449),
                            Name = "Chicken Breast Baked"
                        },
                        new
                        {
                            Id = new Guid("0d9e54c7-0c33-4f2c-b3d6-43a7d6c0c31f"),
                            Calories = "176",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8454),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8455),
                            Name = "Chicken Breast Grilled"
                        },
                        new
                        {
                            Id = new Guid("c48db9fd-67ae-4a14-95c2-be70e04f5d53"),
                            Calories = "226",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8461),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8462),
                            Name = "Chicken Leg Drumstick And Thigh Baked"
                        },
                        new
                        {
                            Id = new Guid("0aa21e4e-36c0-419f-aa3f-be1c17d60ed6"),
                            Calories = "190",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8494),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8495),
                            Name = "Chicken Drumstick Baked"
                        },
                        new
                        {
                            Id = new Guid("b1a92413-b1f7-4650-9d30-f787bae464d7"),
                            Calories = "200",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8502),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8503),
                            Name = "Chicken Drumstick Grilled"
                        },
                        new
                        {
                            Id = new Guid("36213f15-3b21-46cc-9d69-fa8e8d5f9749"),
                            Calories = "211",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8515),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8516),
                            Name = "Chicken Drumstick Fried"
                        },
                        new
                        {
                            Id = new Guid("c39184f7-4bad-41b9-8b86-af9c53c7bae8"),
                            Calories = "182",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8522),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8523),
                            Name = "Wild Atlantic Salmon"
                        },
                        new
                        {
                            Id = new Guid("93779674-8410-405f-aec8-f92f1f973e65"),
                            Calories = "117",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8529),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8530),
                            Name = "Smoked Salmon"
                        },
                        new
                        {
                            Id = new Guid("ae17c7ab-b721-41ee-bf49-f773437de0cf"),
                            Calories = "167",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8535),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8536),
                            Name = "Canned Salmon"
                        },
                        new
                        {
                            Id = new Guid("e33f8291-5ed9-4f82-814c-c2d1a435b135"),
                            Calories = "136",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8541),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8541),
                            Name = "Canned Pink Salmon"
                        },
                        new
                        {
                            Id = new Guid("ff02fb30-866a-4c14-be88-a55041471d5e"),
                            Calories = "206",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8546),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8547),
                            Name = "Farmed Atlantic Salmon"
                        },
                        new
                        {
                            Id = new Guid("53fd8fac-4f65-43a0-8bc4-9dfb54912184"),
                            Calories = "183",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8553),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8553),
                            Name = "Salmon Baked"
                        },
                        new
                        {
                            Id = new Guid("daad382e-2379-42b6-8ea9-92ceb5932198"),
                            Calories = "71",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8555),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8556),
                            Name = "Fortified Fruit Juice Smoothie"
                        },
                        new
                        {
                            Id = new Guid("00ed38b1-91d4-4a61-ae10-66cab9a49e01"),
                            Calories = "52",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8564),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8565),
                            Name = "Apples"
                        },
                        new
                        {
                            Id = new Guid("842145cc-e74f-497f-a565-24e40f3b0f38"),
                            Calories = "48",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8567),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8567),
                            Name = "Apples (Without Skin)"
                        },
                        new
                        {
                            Id = new Guid("50f8a7fe-2f02-4553-8b9a-054f16409952"),
                            Calories = "89",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8569),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(8570),
                            Name = "Bananas"
                        });
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("Bmi")
                        .HasColumnType("float");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentFitness")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FitnessGoal")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StartingWeight")
                        .HasColumnType("float");

                    b.Property<double>("TargetWeight")
                        .HasColumnType("float");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a2cfe837-1bb4-4375-bd69-67b6cb8436b7",
                            AccessFailedCount = 0,
                            Age = 23,
                            Bmi = 1.8899999999999999,
                            ConcurrencyStamp = "50ab0ba5-eb8d-4af4-b001-926eb2f92a36",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(9191),
                            CurrentFitness = 1,
                            Email = "superuserD@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            FitnessGoal = 1,
                            Height = 1.8300000000000001,
                            IsActive = true,
                            IsDeleted = false,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(9193),
                            NormalizedEmail = "SUPERUSERD@GMAIL.COM",
                            NormalizedUserName = "SUPERUSER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHD4PNVP/Isdx5h/1oDXPX8VB8TOFRrFKSrsEifDE3EqOEJfFT5ctX4wANLdcwlIdg==",
                            PhoneNumber = "08130927418",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8aa624a2-02d6-45b9-9370-01e0a6e1a2ff",
                            StartingWeight = 80.0,
                            TargetWeight = 0.0,
                            TwoFactorEnabled = false,
                            UserName = "superuser@gmail.com"
                        },
                        new
                        {
                            Id = "7f8d80de-2ede-430c-a62a-3f1e2b8167d0",
                            AccessFailedCount = 0,
                            Age = 23,
                            Bmi = 1.8899999999999999,
                            ConcurrencyStamp = "90db7eeb-15d5-45ef-9b65-4c45612e3888",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(9335),
                            CurrentFitness = 1,
                            Email = "osinfadeidris@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Idris",
                            FitnessGoal = 1,
                            Height = 1.8300000000000001,
                            IsActive = true,
                            IsDeleted = false,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Osinfade",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 19, 54, 620, DateTimeKind.Utc).AddTicks(9335),
                            NormalizedEmail = "OSINFADEIDRIS@GMAIL.COM",
                            NormalizedUserName = "OSINFADEIDRIS@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHD4PNVP/Isdx5h/1oDXPX8VB8TOFRrFKSrsEifDE3EqOEJfFT5ctX4wANLdcwlIdg==",
                            PhoneNumber = "07069576909",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f5432fcd-93ea-4454-9fba-293b632bc688",
                            StartingWeight = 80.0,
                            TargetWeight = 0.0,
                            TwoFactorEnabled = false,
                            UserName = "osinfadeidris@gmail.com"
                        });
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.VerificationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("Expiry")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VerificationOtps");
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.WorkOutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.WorkoutProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ExpertiseLevel")
                        .HasColumnType("int");

                    b.Property<string>("WorkoutName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPrograms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df1c3c22-bd6e-4cfc-823b-17af5feb13ba"),
                            Category = 1,
                            ExpertiseLevel = 2,
                            WorkoutName = "20 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("368df685-c375-4333-910d-f4f6f9a8da77"),
                            Category = 4,
                            ExpertiseLevel = 2,
                            WorkoutName = "20 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("f6bfb2b0-fb3e-45b0-8b02-f9eb035e77fe"),
                            Category = 1,
                            ExpertiseLevel = 1,
                            WorkoutName = "30 Minute Cardio Workout"
                        },
                        new
                        {
                            Id = new Guid("622ca00f-015f-42f3-9b3f-b815ba425a47"),
                            Category = 1,
                            ExpertiseLevel = 2,
                            WorkoutName = "45 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("753f337d-af54-4ac6-a41f-b34505dc8784"),
                            Category = 1,
                            ExpertiseLevel = 3,
                            WorkoutName = "45 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("f36a1933-a3b7-4efb-9526-425ac096f8cd"),
                            Category = 2,
                            ExpertiseLevel = 2,
                            WorkoutName = "45 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("e0249b9f-3e36-47a4-9c2b-52c64a7a5df3"),
                            Category = 2,
                            ExpertiseLevel = 3,
                            WorkoutName = "45 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("627b9077-82a3-490c-858c-b6421a33aeee"),
                            Category = 4,
                            ExpertiseLevel = 2,
                            WorkoutName = "45 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("c32a2764-b48e-4aa1-a0e0-032249e6670f"),
                            Category = 4,
                            ExpertiseLevel = 3,
                            WorkoutName = "45 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("bfe4d2d3-6f68-4ffd-9cc4-f59a7f7a609d"),
                            Category = 3,
                            ExpertiseLevel = 1,
                            WorkoutName = "Beginner Strength Training Workout"
                        },
                        new
                        {
                            Id = new Guid("f0243bfa-e315-4480-87d2-2e4798978ee8"),
                            Category = 1,
                            ExpertiseLevel = 2,
                            WorkoutName = "Intermediate Fat Loss Workout"
                        },
                        new
                        {
                            Id = new Guid("aa2eb0e7-da29-4a4d-814f-73fa6cc7c435"),
                            Category = 1,
                            ExpertiseLevel = 3,
                            WorkoutName = "Intermediate Fat Loss Workout"
                        },
                        new
                        {
                            Id = new Guid("61c9090d-8fdd-45f0-b2bd-403778725b11"),
                            Category = 4,
                            ExpertiseLevel = 2,
                            WorkoutName = "Intermediate Fat Loss Workout"
                        },
                        new
                        {
                            Id = new Guid("1de8e8ee-482c-4857-bcf9-eeeb70441e79"),
                            Category = 4,
                            ExpertiseLevel = 3,
                            WorkoutName = "Intermediate Fat Loss Workout"
                        },
                        new
                        {
                            Id = new Guid("225387fd-8c5e-4861-bc6d-116eb3140904"),
                            Category = 1,
                            ExpertiseLevel = 1,
                            WorkoutName = "Beginner At Home Workout"
                        });
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.VerificationOtp", b =>
                {
                    b.HasOne("FitByBitApiService.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
