// <auto-generated />
using System;
using FitByBitApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitByBitApiService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240428161435_Updated workout plan data")]
    partial class Updatedworkoutplandata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FitByBitApiService.Entities.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f4721f9-6abb-4872-b2b1-aebd21bfa12a"),
                            ExerciseName = "Forward Lunge",
                            Name = "20 Minute HIIT Workout",
                            Number = "1",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("80ad7865-15ff-4801-8429-f5a8275d2e10"),
                            ExerciseName = "Bodyweight Squat",
                            Name = "20 Minute HIIT Workout",
                            Number = "2",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("6bd2acad-5ec1-48fd-a879-629e188891c0"),
                            ExerciseName = "Mountain Climber",
                            Name = "20 Minute HIIT Workout",
                            Number = "3",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("e030679a-4720-4d3c-b65c-dda6e11937bc"),
                            ExerciseName = "Jogging in Place",
                            Name = "20 Minute HIIT Workout",
                            Number = "4",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("4837d611-954e-4b3c-a4da-600d87ff37ca"),
                            ExerciseName = "Burpees",
                            Name = "20 Minute HIIT Workout",
                            Number = "5",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("ae942638-b869-4440-9e8e-5060ec24f254"),
                            ExerciseName = "High Kick",
                            Name = "20 Minute HIIT Workout",
                            Number = "6",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("0d77e423-e9a8-417c-8779-7a06bd855d9c"),
                            ExerciseName = "Jumping Jacks",
                            Name = "30 Minute Cardio Workout",
                            Number = "1",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("1da5a2db-fae4-4fd0-8e89-25fed00ab7f1"),
                            ExerciseName = "Push Ups",
                            Name = "30 Minute Cardio Workout",
                            Number = "2",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("0cfa7d68-ca10-476e-b636-6800429891ae"),
                            ExerciseName = "Crunches",
                            Name = "30 Minute Cardio Workout",
                            Number = "3",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("3804d326-ecdc-4c80-8206-31d7f7d630f1"),
                            ExerciseName = "Squat Jumps",
                            Name = "30 Minute Cardio Workout",
                            Number = "4",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("49af64bc-6c4d-4d1b-a11e-659ace56b9c0"),
                            ExerciseName = "Mountain Climber",
                            Name = "30 Minute Cardio Workout",
                            Number = "5",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("6c3d5c48-93d4-4301-81a0-29c55156e261"),
                            ExerciseName = "Burpees",
                            Name = "30 Minute Cardio Workout",
                            Number = "6",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("f99ae51d-f677-48df-92e2-45ebb203b327"),
                            ExerciseName = "Jogging in Place",
                            Name = "30 Minute Cardio Workout",
                            Number = "7",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("243ded1c-8b25-4d43-95a5-3a5b28bbfb41"),
                            ExerciseName = "Jumping Lunges",
                            Name = "30 Minute Cardio Workout",
                            Number = "8",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("dfda5b36-fb4b-4855-96cc-a18e59b94b0b"),
                            ExerciseName = "Burpees",
                            Name = "45 Minute HIIT Workout",
                            Number = "1",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("d0758da5-f9ff-486e-b159-9bc518506cdc"),
                            ExerciseName = "Squat Jumps",
                            Name = "45 Minute HIIT Workout",
                            Number = "2",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("9205861b-3d51-4d80-9de9-fd045af7214e"),
                            ExerciseName = "Crunches",
                            Name = "45 Minute HIIT Workout",
                            Number = "3",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("6515b866-9d01-4e75-9feb-76cc0e99f166"),
                            ExerciseName = "Jumping Jacks",
                            Name = "45 Minute HIIT Workout",
                            Number = "4",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("e23a003d-7243-474f-b6f5-cc194c37eef1"),
                            ExerciseName = "Jumping Lunges",
                            Name = "45 Minute HIIT Workout",
                            Number = "5",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("1bf98e46-35f1-4df8-938d-27bfbfc07626"),
                            ExerciseName = "Push Ups",
                            Name = "45 Minute HIIT Workout",
                            Number = "6",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("9f166ff3-88be-4536-a7a7-3de6e8e1b9d1"),
                            ExerciseName = "Deadlift",
                            Name = "Beginner Strength Training Workout",
                            Number = "1",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("44494c61-5114-4857-a800-c7c39c2eb908"),
                            ExerciseName = "Leg Press",
                            Name = "Beginner Strength Training Workout",
                            Number = "2",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("c0a9b410-379c-4155-af2b-04341d8ea96e"),
                            ExerciseName = "Walking Lunge",
                            Name = "Beginner Strength Training Workout",
                            Number = "3",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("3b6c39cc-9ce5-4501-a17f-2e7d11dd5203"),
                            ExerciseName = "Cruches",
                            Name = "Beginner Strength Training Workout",
                            Number = "4",
                            Reps = "12, 12, 12",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("d5dbdf24-59cf-4f18-b342-58dd39f0dea4"),
                            ExerciseName = "Lateral Raise",
                            Name = "Beginner Strength Training Workout",
                            Number = "5",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("c1c29222-2bae-4318-8c74-dda00f7f86ff"),
                            ExerciseName = "Hammer Dumbbell Curl",
                            Name = "Beginner Strength Training Workout",
                            Number = "6",
                            Reps = "12, 10, 9",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("afe39901-27c6-48c8-8e4d-6310b96f6a9f"),
                            ExerciseName = "Goblet Squat",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "1",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("4699cb07-2d8c-4d1e-aa54-07999e6b524b"),
                            ExerciseName = "Stiff Leg Deadlift",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "2",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("14197d08-28fc-4405-9ed6-456101d44839"),
                            ExerciseName = "Leg Press",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "3",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("626aa459-e78d-457c-9a27-5fbab397482b"),
                            ExerciseName = "Walking Lunge",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "4",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("513dc837-7aa2-40d6-85f7-056ea6dd427f"),
                            ExerciseName = "Seated Calf Raise",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "5",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("744830c3-d09f-481c-9dfc-2da3170c37d1"),
                            ExerciseName = "Crunches",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "6",
                            Reps = "12, 12, 12",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("bbca0b79-fcdf-4f74-b304-770566364d58"),
                            ExerciseName = "Lateral Raise",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "7",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("55c8205b-2563-486b-9b00-605235cd2c22"),
                            ExerciseName = "Hammer Dumbbell Curl",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "8",
                            Reps = "12, 10, 9",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("9a900b76-ba88-429e-83eb-a27f964c9d01"),
                            ExerciseName = "Straight Bar Tricep Extension",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "9",
                            Reps = "12, 10, 10",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("98bc6bb7-1e67-4857-9f25-e2b1be959c23"),
                            ExerciseName = "Burpee",
                            Name = "Beginner At Home Workout",
                            Number = "1",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("2e3982b6-a833-4f06-8ca2-cf998e4084ec"),
                            ExerciseName = "Push Up",
                            Name = "Beginner At Home Workout",
                            Number = "2",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("d17e213d-8fd5-4fbe-9be5-82d1944b654c"),
                            ExerciseName = "Floor Crunch",
                            Name = "Beginner At Home Workout",
                            Number = "3",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("5820a52d-2270-444d-a908-fd85566b2426"),
                            ExerciseName = "Squat Jump",
                            Name = "Beginner At Home Workout",
                            Number = "4",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("654d9ba6-7209-459c-8e04-f0c5fcd5abed"),
                            ExerciseName = "Bicycle Crunch",
                            Name = "Beginner At Home Workout",
                            Number = "5",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("38c222bd-0a2f-40d9-81a4-6fb94c2fe222"),
                            ExerciseName = "Mountain Climber",
                            Name = "Beginner At Home Workout",
                            Number = "6",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("c863f463-f6c7-42d1-bfd0-951a2c5a93ee"),
                            ExerciseName = "Reverse or Walking Lunge",
                            Name = "Beginner At Home Workout",
                            Number = "7",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("83ad39d8-d026-4bf9-a08d-94048f878da8"),
                            ExerciseName = "Star Jumps",
                            Name = "Beginner At Home Workout",
                            Number = "8",
                            Set = "2",
                            Time = "1 min"
                        });
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Calories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f0e9b4e-099b-45c1-a807-e9caf640daeb"),
                            Calories = "130",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(3916),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(3931),
                            Name = "White Rice"
                        },
                        new
                        {
                            Id = new Guid("d494d8dd-29e5-43c3-99c8-dfed4856c16f"),
                            Calories = "130",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4008),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4009),
                            Name = "Medium Grain White Rice"
                        },
                        new
                        {
                            Id = new Guid("5388596a-b676-4f25-848b-aecf230ca74e"),
                            Calories = "108",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4016),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4017),
                            Name = "Rice Noodles (Cooked)"
                        },
                        new
                        {
                            Id = new Guid("9ead5d36-9c75-4252-890a-5ada2476ba0f"),
                            Calories = "123",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4022),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4023),
                            Name = "Brown Rice"
                        },
                        new
                        {
                            Id = new Guid("06781617-2e3b-4aaa-8fe7-af5e78e07dd7"),
                            Calories = "145",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4027),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4030),
                            Name = "Beef And Rice No Sauce"
                        },
                        new
                        {
                            Id = new Guid("8ae73978-aa0a-4162-8df8-1f94b6f7cbe4"),
                            Calories = "136",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4040),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4041),
                            Name = "Beef And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("d1f89952-5175-4db6-b544-fdbe00f35305"),
                            Calories = "112",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4047),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4048),
                            Name = "Chili Con Carne With Beans And Rice"
                        },
                        new
                        {
                            Id = new Guid("ee2c1d77-bbe8-41c1-9164-a5d1ae02cdf2"),
                            Calories = "139",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4053),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4054),
                            Name = "Pork And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("ef98de22-3e24-4b7b-ada0-b8ae8e9d6570"),
                            Calories = "148",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4080),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4081),
                            Name = "Chicken Or Turkey And Rice No Sauce"
                        },
                        new
                        {
                            Id = new Guid("54839a10-8739-4c45-9bf2-0b5f55f06359"),
                            Calories = "141",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4090),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4091),
                            Name = "Chicken Or Turkey And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("32b8cf3a-d98f-4b2e-a92f-7df12e491ad2"),
                            Calories = "135",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4096),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4098),
                            Name = "Fish And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("5b62fc11-e62e-41c2-bf4a-dd9177954281"),
                            Calories = "147",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4102),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4105),
                            Name = "Beef, Rice And Vegetables"
                        },
                        new
                        {
                            Id = new Guid("e7d8cd85-7518-4b99-91d8-3d0610b5c8b4"),
                            Calories = "128",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4107),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4108),
                            Name = "Pork, Rice And Vegetables "
                        },
                        new
                        {
                            Id = new Guid("93c4bceb-4b98-4580-b086-f148c8af2963"),
                            Calories = "381",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4110),
                            FoodGroup = "3",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4110),
                            Name = "Cereal (Kellogg's Rice Krispies)"
                        },
                        new
                        {
                            Id = new Guid("44a646cb-d6a3-49a0-a1c6-adaee01d4dc5"),
                            Calories = "149",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4114),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4115),
                            Name = "Whole Wheat Pasta"
                        },
                        new
                        {
                            Id = new Guid("1f0fabd6-37b2-4302-906e-25ada5a7d1a8"),
                            Calories = "157",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4123),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4123),
                            Name = "Pasta Cooked"
                        },
                        new
                        {
                            Id = new Guid("f4da3b22-5f35-4c1f-b9ac-7a30e2410afe"),
                            Calories = "148",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4130),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4131),
                            Name = "Pasta Whole Grain Cooked"
                        },
                        new
                        {
                            Id = new Guid("3ab35174-8ba6-4958-b302-62cd38cf4775"),
                            Calories = "192",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4135),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4136),
                            Name = "Chicken Breast Baked"
                        },
                        new
                        {
                            Id = new Guid("a307dc98-ca07-447a-a1d4-de6ffa5215c1"),
                            Calories = "176",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4140),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4141),
                            Name = "Chicken Breast Grilled"
                        },
                        new
                        {
                            Id = new Guid("90c66216-b4be-4324-b2a9-193d90d43621"),
                            Calories = "226",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4143),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4143),
                            Name = "Chicken Leg Drumstick And Thigh Baked"
                        },
                        new
                        {
                            Id = new Guid("a97f8a2a-3dd1-4b9e-a1c8-ae7556d7df5d"),
                            Calories = "190",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4145),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4146),
                            Name = "Chicken Drumstick Baked"
                        },
                        new
                        {
                            Id = new Guid("9bab38da-61b6-433c-92ff-032810334699"),
                            Calories = "200",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4150),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4150),
                            Name = "Chicken Drumstick Grilled"
                        },
                        new
                        {
                            Id = new Guid("d2500413-de4b-4332-a5da-233de962786f"),
                            Calories = "211",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4152),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4153),
                            Name = "Chicken Drumstick Fried"
                        },
                        new
                        {
                            Id = new Guid("a934b1ff-4bcc-436f-bab0-61aa6f6f25d0"),
                            Calories = "182",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4155),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4155),
                            Name = "Wild Atlantic Salmon"
                        },
                        new
                        {
                            Id = new Guid("c5da3e2d-a4f5-479f-911b-1fa45a902616"),
                            Calories = "117",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4162),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4163),
                            Name = "Smoked Salmon"
                        },
                        new
                        {
                            Id = new Guid("a3cb0178-5ba9-4a1f-bf75-1827dd96eaf9"),
                            Calories = "167",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4165),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4165),
                            Name = "Canned Salmon"
                        },
                        new
                        {
                            Id = new Guid("c1fa7a3b-e250-4144-90d8-cc1bcc32ed80"),
                            Calories = "136",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4168),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4168),
                            Name = "Canned Pink Salmon"
                        },
                        new
                        {
                            Id = new Guid("755eca5a-9435-44c4-9431-5245aed7cebf"),
                            Calories = "206",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4170),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4170),
                            Name = "Farmed Atlantic Salmon"
                        },
                        new
                        {
                            Id = new Guid("4b589429-9630-4a05-9234-f63995521db1"),
                            Calories = "183",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4172),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4173),
                            Name = "Salmon Baked"
                        },
                        new
                        {
                            Id = new Guid("544f0d8b-4904-44b4-bd21-41e1ae654b0b"),
                            Calories = "71",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4175),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4176),
                            Name = "Fortified Fruit Juice Smoothie"
                        },
                        new
                        {
                            Id = new Guid("75631f7c-8043-4b35-b28b-c5fcf117e8c6"),
                            Calories = "52",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4178),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4178),
                            Name = "Apples"
                        },
                        new
                        {
                            Id = new Guid("5e865165-c157-4131-a0d5-fcf82541e7c4"),
                            Calories = "48",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4181),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4181),
                            Name = "Apples (Without Skin)"
                        },
                        new
                        {
                            Id = new Guid("da21ffbd-2592-4db8-9c5e-a6f1b4651170"),
                            Calories = "89",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4187),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4188),
                            Name = "Bananas"
                        });
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("Bmi")
                        .HasColumnType("float");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentFitness")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FitnessGoal")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StartingWeight")
                        .HasColumnType("float");

                    b.Property<double>("TargetWeight")
                        .HasColumnType("float");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "95543187-a674-4517-965c-9ac5e1301364",
                            AccessFailedCount = 0,
                            Age = 23,
                            Bmi = 1.8899999999999999,
                            ConcurrencyStamp = "66e81725-7915-4d4b-833a-af6192510ba8",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4514),
                            CurrentFitness = 1,
                            Email = "superuserD@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            FitnessGoal = 1,
                            Height = 1.8300000000000001,
                            IsActive = true,
                            IsDeleted = false,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4516),
                            NormalizedEmail = "SUPERUSERD@GMAIL.COM",
                            NormalizedUserName = "SUPERUSER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDAYmKLuazFYHkQuMfL08XsrZuMngsiZQ6m1iU+1braZY1UODHIb5ynLL9Uo7Mkv8w==",
                            PhoneNumber = "08130927418",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8fcb1571-fc55-4352-88a4-a3d28724191e",
                            StartingWeight = 80.0,
                            TargetWeight = 0.0,
                            TwoFactorEnabled = false,
                            UserName = "superuser@gmail.com"
                        },
                        new
                        {
                            Id = "b1997fcb-d06a-48c8-aebf-e47f5c528784",
                            AccessFailedCount = 0,
                            Age = 23,
                            Bmi = 1.8899999999999999,
                            ConcurrencyStamp = "52898060-e4a0-4b23-9003-89abc703b8a9",
                            CreatedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4589),
                            CurrentFitness = 1,
                            Email = "osinfadeidris@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Idris",
                            FitnessGoal = 1,
                            Height = 1.8300000000000001,
                            IsActive = true,
                            IsDeleted = false,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Osinfade",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 4, 28, 16, 14, 34, 698, DateTimeKind.Utc).AddTicks(4590),
                            NormalizedEmail = "OSINFADEIDRIS@GMAIL.COM",
                            NormalizedUserName = "OSINFADEIDRIS@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDAYmKLuazFYHkQuMfL08XsrZuMngsiZQ6m1iU+1braZY1UODHIb5ynLL9Uo7Mkv8w==",
                            PhoneNumber = "07069576909",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "864a101d-d7fe-49c8-8962-735dccb803e3",
                            StartingWeight = 80.0,
                            TargetWeight = 0.0,
                            TwoFactorEnabled = false,
                            UserName = "osinfadeidris@gmail.com"
                        });
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.VerificationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("Expiry")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VerificationOtps");
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.WorkOutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.WorkoutProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ExpertiseLevel")
                        .HasColumnType("int");

                    b.Property<string>("WorkoutName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPrograms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a43691b3-bb46-4925-90a7-be0b162dbd42"),
                            Category = 1,
                            ExpertiseLevel = 2,
                            WorkoutName = "20 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("b81a796e-8868-415d-a6b4-2d2e6638f57d"),
                            Category = 4,
                            ExpertiseLevel = 2,
                            WorkoutName = "20 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("3e981da5-9fcd-41ea-8c6a-9040c491558d"),
                            Category = 1,
                            ExpertiseLevel = 1,
                            WorkoutName = "30 Minute Cardio Workout"
                        },
                        new
                        {
                            Id = new Guid("298d7848-c175-4ea0-ae0d-9f91eae36510"),
                            Category = 1,
                            ExpertiseLevel = 2,
                            WorkoutName = "45 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("88386020-1eb6-4694-b7ec-fbaec1be7519"),
                            Category = 1,
                            ExpertiseLevel = 3,
                            WorkoutName = "45 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("7fa81f8d-420c-410e-bf68-94cd6d7152c7"),
                            Category = 2,
                            ExpertiseLevel = 2,
                            WorkoutName = "45 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("ab3e9db3-85a8-4998-82c8-e06076c59608"),
                            Category = 2,
                            ExpertiseLevel = 3,
                            WorkoutName = "45 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("0796dcf4-50a9-4cd0-88a5-942c420a56b8"),
                            Category = 4,
                            ExpertiseLevel = 2,
                            WorkoutName = "45 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("357cf694-6103-4255-8fe8-66a91ff26408"),
                            Category = 4,
                            ExpertiseLevel = 3,
                            WorkoutName = "45 Minute HIIT Workout"
                        },
                        new
                        {
                            Id = new Guid("a3437be5-1faf-419e-aebc-89722f0530ec"),
                            Category = 3,
                            ExpertiseLevel = 1,
                            WorkoutName = "Beginner Strength Training Workout"
                        },
                        new
                        {
                            Id = new Guid("6bff9450-0b27-40c4-97a1-1a887aabc94e"),
                            Category = 1,
                            ExpertiseLevel = 2,
                            WorkoutName = "Intermediate Fat Loss Workout"
                        },
                        new
                        {
                            Id = new Guid("c126124f-3c8d-46f6-86f9-7a389d7f7945"),
                            Category = 1,
                            ExpertiseLevel = 3,
                            WorkoutName = "Intermediate Fat Loss Workout"
                        },
                        new
                        {
                            Id = new Guid("a7135fae-3e7f-4ffc-83eb-90c169fc3be0"),
                            Category = 4,
                            ExpertiseLevel = 2,
                            WorkoutName = "Intermediate Fat Loss Workout"
                        },
                        new
                        {
                            Id = new Guid("f54c250c-4ada-40db-8fc1-af5194979d22"),
                            Category = 4,
                            ExpertiseLevel = 3,
                            WorkoutName = "Intermediate Fat Loss Workout"
                        },
                        new
                        {
                            Id = new Guid("138e1ef5-8838-4be0-8e25-36af74e7f392"),
                            Category = 1,
                            ExpertiseLevel = 1,
                            WorkoutName = "Beginner At Home Workout"
                        });
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.VerificationOtp", b =>
                {
                    b.HasOne("FitByBitApiService.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
