// <auto-generated />
using System;
using FitByBitService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitByBitApiService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240324200225_Publishing")]
    partial class Publishing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FitByBitApiService.Entities.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e109af33-5c1c-4c19-b27a-3c100d5992f2"),
                            ExerciseName = "Forward Lunge",
                            Name = "20 Minute HIIT Workout",
                            Number = "1",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("692d9157-15f9-410b-9844-61840f7a3771"),
                            ExerciseName = "Bodyweight Squat",
                            Name = "20 Minute HIIT Workout",
                            Number = "2",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("96c427c9-a931-4d7a-bf4f-fda70f7c4f9e"),
                            ExerciseName = "Mountain Climber",
                            Name = "20 Minute HIIT Workout",
                            Number = "3",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("a983465a-d157-4059-9bdd-e2dbe6013b61"),
                            ExerciseName = "Jogging in Place",
                            Name = "20 Minute HIIT Workout",
                            Number = "4",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("b3ea7b44-c921-4a15-82aa-22e1bd9b1e97"),
                            ExerciseName = "Burpees",
                            Name = "20 Minute HIIT Workout",
                            Number = "5",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("919908a3-b802-40d4-8213-57843b18be4b"),
                            ExerciseName = "High Kick",
                            Name = "20 Minute HIIT Workout",
                            Number = "6",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("9798c406-797b-48d0-9e14-8e0db564bb60"),
                            ExerciseName = "Jumping Jacks",
                            Name = "30 Minute Cardio Workout",
                            Number = "1",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("fa1df10e-da7a-46fa-9309-3631081b367b"),
                            ExerciseName = "Push Ups",
                            Name = "30 Minute Cardio Workout",
                            Number = "2",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("5179a590-59fe-4d00-9b19-b2d7de416336"),
                            ExerciseName = "Crunches",
                            Name = "30 Minute Cardio Workout",
                            Number = "3",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("a928f1c2-02bd-4a7c-a3f0-b9fbb1cc4ffc"),
                            ExerciseName = "Squat Jumps",
                            Name = "30 Minute Cardio Workout",
                            Number = "4",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("ac747251-9432-42c2-a6b1-8716b5d87f51"),
                            ExerciseName = "Mountain Climber",
                            Name = "30 Minute Cardio Workout",
                            Number = "5",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("457cd7b9-a5f5-41d4-8f8d-0413a7598edf"),
                            ExerciseName = "Burpees",
                            Name = "30 Minute Cardio Workout",
                            Number = "6",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("e2b88506-10dc-4a92-8511-67f6f8f8890f"),
                            ExerciseName = "Jogging in Place",
                            Name = "30 Minute Cardio Workout",
                            Number = "7",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("f735c7c4-b093-416b-abc7-40272139032e"),
                            ExerciseName = "Jumping Lunges",
                            Name = "30 Minute Cardio Workout",
                            Number = "8",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("6d7c4ec0-c0de-4082-8db2-3ea876419750"),
                            ExerciseName = "Burpees",
                            Name = "45 Minute HIIT Workout",
                            Number = "1",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("591394dd-b44d-4459-9247-022ebc5efbfd"),
                            ExerciseName = "Squat Jumps",
                            Name = "45 Minute HIIT Workout",
                            Number = "2",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("31cb19c7-e815-454c-abbc-d32374c5a6c6"),
                            ExerciseName = "Crunches",
                            Name = "45 Minute HIIT Workout",
                            Number = "3",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("90b6ca6e-03eb-482a-a919-3ad0784bb200"),
                            ExerciseName = "Jumping Jacks",
                            Name = "45 Minute HIIT Workout",
                            Number = "4",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("518ad58d-e176-4ab5-b24c-159e9fc8e2bf"),
                            ExerciseName = "Jumping Lunges",
                            Name = "45 Minute HIIT Workout",
                            Number = "5",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("408cd5a2-08de-468b-b354-93b4b94180ca"),
                            ExerciseName = "Push Ups",
                            Name = "45 Minute HIIT Workout",
                            Number = "6",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("09a1ed6c-f51d-422b-8293-9ffd6a49d46c"),
                            ExerciseName = "Deadlift",
                            Name = "Beginner Strength Training Workout",
                            Number = "1",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("c8c32d81-3a81-42b5-98de-d7852d5689a9"),
                            ExerciseName = "Leg Press",
                            Name = "Beginner Strength Training Workout",
                            Number = "2",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("2e385b79-7bcd-4368-b7ec-fe20dbd02b8b"),
                            ExerciseName = "Walking Lunge",
                            Name = "Beginner Strength Training Workout",
                            Number = "3",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("bacc7051-6c35-48a1-bbab-2bd96f11fe1e"),
                            ExerciseName = "Cruches",
                            Name = "Beginner Strength Training Workout",
                            Number = "4",
                            Reps = "12, 12, 12",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("1cf46cc4-c51b-440a-9af9-2a1f5ad7b1e8"),
                            ExerciseName = "Lateral Raise",
                            Name = "Beginner Strength Training Workout",
                            Number = "5",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("bcf64ccb-ce3e-44fa-b00a-97f43aab5200"),
                            ExerciseName = "Hammer Dumbbell Curl",
                            Name = "Beginner Strength Training Workout",
                            Number = "6",
                            Reps = "12, 10, 9",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("963cc095-8005-4b4e-b37b-b06cc252dbbd"),
                            ExerciseName = "Goblet Squat",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "1",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("b9508742-25ed-416b-9e72-dc9d47bc8b71"),
                            ExerciseName = "Stiff Leg Deadlift",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "2",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("682db761-7c12-4200-ad69-e70bfddda5cb"),
                            ExerciseName = "Leg Press",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "3",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("e54e4316-8aa4-4a63-a26f-bd1a4223113b"),
                            ExerciseName = "Walking Lunge",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "4",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("d7a4ce00-ae65-44a9-8a6c-e14bbc255cb8"),
                            ExerciseName = "Seated Calf Raise",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "5",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("deaa9976-d8a6-4b13-89b0-ffa0c08d2caa"),
                            ExerciseName = "Crunches",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "6",
                            Reps = "12, 12, 12",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("a82c8cfd-6e98-4bff-bc39-a89a8f172008"),
                            ExerciseName = "Lateral Raise",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "7",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("f748167f-2fcf-4045-aa4f-5f580d4dcbd9"),
                            ExerciseName = "Hammer Dumbbell Curl",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "8",
                            Reps = "12, 10, 9",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("c9ac2ec5-2590-429b-907c-16478baee60d"),
                            ExerciseName = "Straight Bar Tricep Extension",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "9",
                            Reps = "12, 10, 10",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("da3d22b0-e238-476e-b864-96d8240807d8"),
                            ExerciseName = "Burpee",
                            Name = "Beginner At Home Workout",
                            Number = "1",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("815e1623-d3d6-49b5-9a52-ed068618e6b8"),
                            ExerciseName = "Push Up",
                            Name = "Beginner At Home Workout",
                            Number = "2",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("66fed5ce-3869-4c30-934f-cbbeb7bd970b"),
                            ExerciseName = "Floor Crunch",
                            Name = "Beginner At Home Workout",
                            Number = "3",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("dcb993e6-4550-45ea-ac0d-7b4bc1a4f999"),
                            ExerciseName = "Squat Jump",
                            Name = "Beginner At Home Workout",
                            Number = "4",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("e25cc5d7-5999-42c3-8858-409da5755c26"),
                            ExerciseName = "Bicycle Crunch",
                            Name = "Beginner At Home Workout",
                            Number = "5",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("f9f57f6b-5ab2-4299-afb3-f7c3eb5bcd24"),
                            ExerciseName = "Mountain Climber",
                            Name = "Beginner At Home Workout",
                            Number = "6",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("00dbb0ef-5ad5-48dc-98fc-b3c13a5a95e3"),
                            ExerciseName = "Reverse or Walking Lunge",
                            Name = "Beginner At Home Workout",
                            Number = "7",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("1e28caf4-a699-44ec-9691-b9967b950ddc"),
                            ExerciseName = "Star Jumps",
                            Name = "Beginner At Home Workout",
                            Number = "8",
                            Set = "2",
                            Time = "1 min"
                        });
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.WorkoutProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpertiseLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPrograms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57dcb18d-04ba-4d8f-932e-fb3ff61c872a"),
                            Category = 1,
                            ExerciseName = "20 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("f6f9ecc1-d1e1-4ed8-9548-c57c15310dec"),
                            Category = 4,
                            ExerciseName = "20 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("7f99121e-6a2a-4bc2-a0d3-add339426625"),
                            Category = 1,
                            ExerciseName = "30 Minute Cardio Workout",
                            ExpertiseLevel = 1
                        },
                        new
                        {
                            Id = new Guid("1887507d-5fc1-4bcb-a1d7-166242fce8e8"),
                            Category = 1,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("261e785b-3ec4-4483-a3f2-b2ed6b6e1376"),
                            Category = 1,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("e1516370-df7c-4f0e-9d1c-4c5ad25749aa"),
                            Category = 2,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("16cfe627-93a2-4e20-a572-33c8c006af57"),
                            Category = 2,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("8ff32807-00dd-4d41-a009-9f9852ce4ea8"),
                            Category = 4,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("a83a647e-f7dc-456c-ac44-a99366477e53"),
                            Category = 4,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("53b3cf8f-3485-4cd3-a0fb-0e1b5daaf3d1"),
                            Category = 3,
                            ExerciseName = "Beginner Strength Training Workout",
                            ExpertiseLevel = 1
                        },
                        new
                        {
                            Id = new Guid("28a9d26c-de7e-469f-8a49-211e6464d64f"),
                            Category = 1,
                            ExerciseName = "Intermediate Fat Loss Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("17a3497c-0090-4a79-8cb9-59e4e96ce6a6"),
                            Category = 1,
                            ExerciseName = "Intermediate Fat Loss Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("0e11d2aa-d67c-4bf6-ad3b-33318454bb9f"),
                            Category = 4,
                            ExerciseName = "Intermediate Fat Loss Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("9c1753ff-1754-4311-82ef-e1a2e364370c"),
                            Category = 4,
                            ExerciseName = "Intermediate Fat Loss Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("681963c0-08df-4456-a565-7393b67bf85f"),
                            Category = 1,
                            ExerciseName = "Beginner At Home Workout",
                            ExpertiseLevel = 1
                        });
                });

            modelBuilder.Entity("FitByBitService.Entities.Models.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Calories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94ddfb73-981b-414c-afc1-95f52a2db1e1"),
                            Calories = "130",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7829),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7833),
                            Name = "White Rice"
                        },
                        new
                        {
                            Id = new Guid("38a1083b-d0ff-4eb7-b830-6d3823b69070"),
                            Calories = "130",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7867),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7867),
                            Name = "Medium Grain White Rice"
                        },
                        new
                        {
                            Id = new Guid("5906e1a1-c320-49ed-947f-38b05bdcbdfe"),
                            Calories = "108",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7871),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7871),
                            Name = "Rice Noodles (Cooked)"
                        },
                        new
                        {
                            Id = new Guid("0c9a1d4c-c674-4a44-8380-87288b04af82"),
                            Calories = "123",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7887),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7888),
                            Name = "Brown Rice"
                        },
                        new
                        {
                            Id = new Guid("1e596455-ea45-4d7c-bc74-a15a4b5665c6"),
                            Calories = "145",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7890),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7891),
                            Name = "Beef And Rice No Sauce"
                        },
                        new
                        {
                            Id = new Guid("9a18dc8b-fd11-4c9f-8035-bbc786343955"),
                            Calories = "136",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7897),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7898),
                            Name = "Beef And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("3314ee4d-0b7b-422f-8fda-acc2cbc1d24b"),
                            Calories = "112",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7901),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7901),
                            Name = "Chili Con Carne With Beans And Rice"
                        },
                        new
                        {
                            Id = new Guid("854bcbe6-b81f-4a0c-bf4e-01106ba1e80b"),
                            Calories = "139",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7904),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7904),
                            Name = "Pork And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("d8fe8841-807c-477e-8511-7d968dcdfb9f"),
                            Calories = "148",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7910),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7911),
                            Name = "Chicken Or Turkey And Rice No Sauce"
                        },
                        new
                        {
                            Id = new Guid("6f739565-4fa6-4d9d-a444-8f2176860dfe"),
                            Calories = "141",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7915),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7916),
                            Name = "Chicken Or Turkey And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("799d8e82-4cac-49be-8cfb-49d917d9dd25"),
                            Calories = "135",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7918),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7919),
                            Name = "Fish And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("58a25144-7ccf-487f-8f1d-9505b07e597f"),
                            Calories = "147",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7926),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7927),
                            Name = "Beef, Rice And Vegetables"
                        },
                        new
                        {
                            Id = new Guid("e6975c9b-5b9e-40d9-8ad2-ffae7a98de9b"),
                            Calories = "128",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7929),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7930),
                            Name = "Pork, Rice And Vegetables "
                        },
                        new
                        {
                            Id = new Guid("32c4a4b7-a398-4320-947a-c700086c677e"),
                            Calories = "381",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7933),
                            FoodGroup = "3",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7933),
                            Name = "Cereal (Kellogg's Rice Krispies)"
                        },
                        new
                        {
                            Id = new Guid("534c0446-9d5a-4b7e-ad39-75defb1bca87"),
                            Calories = "149",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7936),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7936),
                            Name = "Whole Wheat Pasta"
                        },
                        new
                        {
                            Id = new Guid("eafdd572-a637-4c76-9ae3-68948ebd0f32"),
                            Calories = "157",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7939),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7939),
                            Name = "Pasta Cooked"
                        },
                        new
                        {
                            Id = new Guid("5a2c69a6-df25-44ab-b6c4-9b8a79d8fcc7"),
                            Calories = "148",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7943),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7943),
                            Name = "Pasta Whole Grain Cooked"
                        },
                        new
                        {
                            Id = new Guid("bb9e296d-6263-4d9b-9e8b-8b8e4685a425"),
                            Calories = "192",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7948),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7948),
                            Name = "Chicken Breast Baked"
                        },
                        new
                        {
                            Id = new Guid("ee605fec-1ea3-456d-8ec8-19e31110e799"),
                            Calories = "176",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7951),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7951),
                            Name = "Chicken Breast Grilled"
                        },
                        new
                        {
                            Id = new Guid("b1c70256-ff12-4a85-af48-e6a13ff698b7"),
                            Calories = "226",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7958),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7959),
                            Name = "Chicken Leg Drumstick And Thigh Baked"
                        },
                        new
                        {
                            Id = new Guid("88e30bbf-d091-497f-b782-0c0d090abbb2"),
                            Calories = "190",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7961),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7962),
                            Name = "Chicken Drumstick Baked"
                        },
                        new
                        {
                            Id = new Guid("0b14628c-9317-43c4-976d-b75f3a6a2a53"),
                            Calories = "200",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7965),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7966),
                            Name = "Chicken Drumstick Grilled"
                        },
                        new
                        {
                            Id = new Guid("c9adc489-5194-4c94-985b-11be8ce2c9f4"),
                            Calories = "211",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7969),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7969),
                            Name = "Chicken Drumstick Fried"
                        },
                        new
                        {
                            Id = new Guid("0becc998-4408-4386-a78f-f3148d5b23cd"),
                            Calories = "182",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7972),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7972),
                            Name = "Wild Atlantic Salmon"
                        },
                        new
                        {
                            Id = new Guid("d5565c55-69c0-4e31-bb8d-d84ee915e731"),
                            Calories = "117",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7975),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7976),
                            Name = "Smoked Salmon"
                        },
                        new
                        {
                            Id = new Guid("1ce5b792-7024-4a75-ab35-944be0b24fab"),
                            Calories = "167",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7978),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7979),
                            Name = "Canned Salmon"
                        },
                        new
                        {
                            Id = new Guid("0f28227e-e6e6-454e-b7d8-5bdb1cba69a8"),
                            Calories = "136",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7982),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7982),
                            Name = "Canned Pink Salmon"
                        },
                        new
                        {
                            Id = new Guid("16069de6-107a-4926-a59c-90e7092c2a88"),
                            Calories = "206",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7988),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7989),
                            Name = "Farmed Atlantic Salmon"
                        },
                        new
                        {
                            Id = new Guid("94325018-7818-4cac-8b8c-bd63a1da30fa"),
                            Calories = "183",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7992),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7992),
                            Name = "Salmon Baked"
                        },
                        new
                        {
                            Id = new Guid("bc5f0ac2-da85-49a0-bd09-571acaf03bf6"),
                            Calories = "71",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7995),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7995),
                            Name = "Fortified Fruit Juice Smoothie"
                        },
                        new
                        {
                            Id = new Guid("bc608b00-4385-4182-a672-841dd43aaecb"),
                            Calories = "52",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7998),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(7999),
                            Name = "Apples"
                        },
                        new
                        {
                            Id = new Guid("937b32b8-58ce-4fbf-8cdd-973ce6548ba5"),
                            Calories = "48",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(8002),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(8002),
                            Name = "Apples (Without Skin)"
                        },
                        new
                        {
                            Id = new Guid("2c1fbd10-e776-4424-97cc-b6f32194eed7"),
                            Calories = "89",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(8004),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(8005),
                            Name = "Bananas"
                        });
                });

            modelBuilder.Entity("FitByBitService.Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("Bmi")
                        .HasColumnType("float");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentFitness")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FitnessGoal")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StartingWeight")
                        .HasColumnType("float");

                    b.Property<double>("TargetWeight")
                        .HasColumnType("float");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fc3ea0ad-7ad2-408a-8311-20f4279b8b04",
                            AccessFailedCount = 0,
                            Age = 23,
                            Bmi = 1.8899999999999999,
                            ConcurrencyStamp = "1ef73f89-b28b-4b34-9343-c6f1870dd480",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(8115),
                            CurrentFitness = 1,
                            Email = "superuserD@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            FitnessGoal = 1,
                            Height = 1.8300000000000001,
                            IsActive = true,
                            IsDeleted = false,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(8116),
                            NormalizedEmail = "SUPERUSERD@GMAIL.COM",
                            NormalizedUserName = "SUPERUSER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECh++xR6INEZJHSVZxrXMOO1QXCR5mAoo08mFGMC+F4OcQtYXx3Sl6t3bY4wK/HttQ==",
                            PhoneNumber = "08130927418",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "1050b348-835a-49b8-8713-f78b1d742447",
                            StartingWeight = 80.0,
                            TargetWeight = 0.0,
                            TwoFactorEnabled = false,
                            UserName = "superuser@gmail.com"
                        },
                        new
                        {
                            Id = "6d8c0550-f1a4-4669-8cd7-ed382e9aaacd",
                            AccessFailedCount = 0,
                            Age = 23,
                            Bmi = 1.8899999999999999,
                            ConcurrencyStamp = "28a83716-0440-4357-9cf8-1bc282422dd4",
                            CreatedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(8189),
                            CurrentFitness = 1,
                            Email = "osinfadeidris@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Idris",
                            FitnessGoal = 1,
                            Height = 1.8300000000000001,
                            IsActive = true,
                            IsDeleted = false,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Osinfade",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 3, 24, 20, 2, 25, 135, DateTimeKind.Utc).AddTicks(8189),
                            NormalizedEmail = "OSINFADEIDRIS@GMAIL.COM",
                            NormalizedUserName = "OSINFADEIDRIS@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECh++xR6INEZJHSVZxrXMOO1QXCR5mAoo08mFGMC+F4OcQtYXx3Sl6t3bY4wK/HttQ==",
                            PhoneNumber = "07069576909",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "d2608a3f-ef5e-42ee-b228-a30451757ed5",
                            StartingWeight = 80.0,
                            TargetWeight = 0.0,
                            TwoFactorEnabled = false,
                            UserName = "osinfadeidris@gmail.com"
                        });
                });

            modelBuilder.Entity("FitByBitService.Entities.Models.VerificationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("Expiry")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VerificationOtps");
                });

            modelBuilder.Entity("FitByBitService.Entities.Models.VerificationOtp", b =>
                {
                    b.HasOne("FitByBitService.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
