// <auto-generated />
using System;
using FitByBitApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitByBitApiService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FitByBitApiService.Entities.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a8e3279-f421-49c9-aa22-4071d3b52945"),
                            ExerciseName = "Forward Lunge",
                            Name = "20 Minute HIIT Workout",
                            Number = "1",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("ffe615f9-6d51-4b66-b91f-cdfb2bd06c70"),
                            ExerciseName = "Bodyweight Squat",
                            Name = "20 Minute HIIT Workout",
                            Number = "2",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("0b0a2b9e-3ae6-4e93-9d4a-0f209df3c3ee"),
                            ExerciseName = "Mountain Climber",
                            Name = "20 Minute HIIT Workout",
                            Number = "3",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("4b40ce62-789f-497f-9a25-b6c052a6821c"),
                            ExerciseName = "Jogging in Place",
                            Name = "20 Minute HIIT Workout",
                            Number = "4",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("b9236923-3644-493c-bae1-c847c65ea911"),
                            ExerciseName = "Burpees",
                            Name = "20 Minute HIIT Workout",
                            Number = "5",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("17f2091e-90a4-48ae-87ee-e585dce59842"),
                            ExerciseName = "High Kick",
                            Name = "20 Minute HIIT Workout",
                            Number = "6",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("1331e673-0958-4d84-937a-991dfd42c4d9"),
                            ExerciseName = "Jumping Jacks",
                            Name = "30 Minute Cardio Workout",
                            Number = "1",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("e3205083-4e91-479d-9676-b66f3bf37652"),
                            ExerciseName = "Push Ups",
                            Name = "30 Minute Cardio Workout",
                            Number = "2",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("216d8825-961f-410f-b32c-b311217c388d"),
                            ExerciseName = "Crunches",
                            Name = "30 Minute Cardio Workout",
                            Number = "3",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("bc854a05-c3f5-4d1c-bb61-96f2306a0c72"),
                            ExerciseName = "Squat Jumps",
                            Name = "30 Minute Cardio Workout",
                            Number = "4",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("a0bbf3a8-382a-4122-8f63-8e50f6146338"),
                            ExerciseName = "Mountain Climber",
                            Name = "30 Minute Cardio Workout",
                            Number = "5",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("2324740f-da71-4db8-af88-fa488faf170d"),
                            ExerciseName = "Burpees",
                            Name = "30 Minute Cardio Workout",
                            Number = "6",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("28ec5a44-1254-4e33-a732-2c129b6df179"),
                            ExerciseName = "Jogging in Place",
                            Name = "30 Minute Cardio Workout",
                            Number = "7",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("5403281e-b58e-4ab2-ab4a-589674ed46c7"),
                            ExerciseName = "Jumping Lunges",
                            Name = "30 Minute Cardio Workout",
                            Number = "8",
                            Rest = "10-20 sec",
                            Time = "40-50 sec"
                        },
                        new
                        {
                            Id = new Guid("a0ba1d0f-f961-433c-b2d3-90322866bf3e"),
                            ExerciseName = "Burpees",
                            Name = "45 Minute HIIT Workout",
                            Number = "1",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("5e8b5bd6-cad5-4b8b-9895-282f0a914881"),
                            ExerciseName = "Squat Jumps",
                            Name = "45 Minute HIIT Workout",
                            Number = "2",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("f4850a3f-ffa7-468c-87a4-0dbff030260b"),
                            ExerciseName = "Crunches",
                            Name = "45 Minute HIIT Workout",
                            Number = "3",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("9fe0bed3-c861-435e-be45-2d36e73133df"),
                            ExerciseName = "Jumping Jacks",
                            Name = "45 Minute HIIT Workout",
                            Number = "4",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("088d60e6-f039-4f92-88f4-c98647fc7eb1"),
                            ExerciseName = "Jumping Lunges",
                            Name = "45 Minute HIIT Workout",
                            Number = "5",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("3f68ff82-cfba-4f3c-ac5a-53a612d528d5"),
                            ExerciseName = "Push Ups",
                            Name = "45 Minute HIIT Workout",
                            Number = "6",
                            Rest = "10 sec",
                            Time = "30 sec"
                        },
                        new
                        {
                            Id = new Guid("89c3e5ca-b9c2-471d-b33f-65adf56d8c4d"),
                            ExerciseName = "Deadlift",
                            Name = "Beginner Strength Training Workout",
                            Number = "1",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("8c75b956-db07-4033-bc3a-ccfd99522b8d"),
                            ExerciseName = "Leg Press",
                            Name = "Beginner Strength Training Workout",
                            Number = "2",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("ca6a7f2c-2dd3-499f-bb03-dc9adfea5319"),
                            ExerciseName = "Walking Lunge",
                            Name = "Beginner Strength Training Workout",
                            Number = "3",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("1c54d6a1-dc0f-4ca1-a030-d04f91369da9"),
                            ExerciseName = "Cruches",
                            Name = "Beginner Strength Training Workout",
                            Number = "4",
                            Reps = "12, 12, 12",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("cd0186df-73ed-4f9e-97f1-2a411259d77c"),
                            ExerciseName = "Lateral Raise",
                            Name = "Beginner Strength Training Workout",
                            Number = "5",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("e41e97a9-b4c7-41a7-869a-8d664e326f8d"),
                            ExerciseName = "Hammer Dumbbell Curl",
                            Name = "Beginner Strength Training Workout",
                            Number = "6",
                            Reps = "12, 10, 9",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("657966cf-ce31-4e44-b3ca-1bc75c02d70a"),
                            ExerciseName = "Goblet Squat",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "1",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("0bbe3c16-60dd-4895-b785-9fcb1366c8e5"),
                            ExerciseName = "Stiff Leg Deadlift",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "2",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("1b47c60a-020b-4314-95f6-56b950329c9b"),
                            ExerciseName = "Leg Press",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "3",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("b4d71a7d-799c-4fe2-8e47-faebdcb94504"),
                            ExerciseName = "Walking Lunge",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "4",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("3858c199-35aa-4aa4-846b-6c651447a83c"),
                            ExerciseName = "Seated Calf Raise",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "5",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("38f62ace-bed1-4a35-a516-3b69b6ff38a6"),
                            ExerciseName = "Crunches",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "6",
                            Reps = "12, 12, 12",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("443cb2e2-de9c-4718-a0fa-e502551d4e4d"),
                            ExerciseName = "Lateral Raise",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "7",
                            Reps = "12, 10, 8",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("54a83681-d68c-4f04-a17c-19189338832d"),
                            ExerciseName = "Hammer Dumbbell Curl",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "8",
                            Reps = "12, 10, 9",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("b2e3dce5-60a5-45b4-80af-2538d66f1fd3"),
                            ExerciseName = "Straight Bar Tricep Extension",
                            Name = "Intermediate Fat Loss Workout",
                            Number = "9",
                            Reps = "12, 10, 10",
                            Set = "3"
                        },
                        new
                        {
                            Id = new Guid("73fdba60-8344-453d-b441-0a8f2157166f"),
                            ExerciseName = "Burpee",
                            Name = "Beginner At Home Workout",
                            Number = "1",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("c9dc17af-62b8-478a-a8af-0a13e74003f8"),
                            ExerciseName = "Push Up",
                            Name = "Beginner At Home Workout",
                            Number = "2",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("ff0ac2ed-84e8-428e-afe6-b588da2a0402"),
                            ExerciseName = "Floor Crunch",
                            Name = "Beginner At Home Workout",
                            Number = "3",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("dfff8c05-9bcc-479e-ab58-adc31ee888ac"),
                            ExerciseName = "Squat Jump",
                            Name = "Beginner At Home Workout",
                            Number = "4",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("cdaa0be3-0c7a-462c-b79e-b87a49f04062"),
                            ExerciseName = "Bicycle Crunch",
                            Name = "Beginner At Home Workout",
                            Number = "5",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("a46fdc98-0980-49f7-82f7-119ee060a9e6"),
                            ExerciseName = "Mountain Climber",
                            Name = "Beginner At Home Workout",
                            Number = "6",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("a0b375dc-5043-4dcb-89d8-c4d1a3f2af54"),
                            ExerciseName = "Reverse or Walking Lunge",
                            Name = "Beginner At Home Workout",
                            Number = "7",
                            Reps = "10-15",
                            Set = "2"
                        },
                        new
                        {
                            Id = new Guid("9ee7e06e-91ac-44ec-88bb-0514b58b18b5"),
                            ExerciseName = "Star Jumps",
                            Name = "Beginner At Home Workout",
                            Number = "8",
                            Set = "2",
                            Time = "1 min"
                        });
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.WorkOutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("FitByBitApiService.Entities.Models.WorkoutProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpertiseLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPrograms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("35f9f304-a15e-401d-bbc9-daa1185f1876"),
                            Category = 1,
                            ExerciseName = "20 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("02c64103-98e5-4f25-aea6-f3d3488270d5"),
                            Category = 4,
                            ExerciseName = "20 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("2ca8966c-7615-4a7c-9c72-b9e53fc2e1a2"),
                            Category = 1,
                            ExerciseName = "30 Minute Cardio Workout",
                            ExpertiseLevel = 1
                        },
                        new
                        {
                            Id = new Guid("c44356c3-d9e6-4328-b46f-0858bc4e754a"),
                            Category = 1,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("1ebd7a1a-7663-450e-81fd-9df3e67f8681"),
                            Category = 1,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("ec5df2e1-6405-4617-ab12-a35046fe176c"),
                            Category = 2,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("4db25770-64a3-4559-8d0a-592a772f39a2"),
                            Category = 2,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("14c1cfa4-1582-4049-8d37-07e406e2dd37"),
                            Category = 4,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("dd690b38-6a49-448d-b6ee-4dd6ffebef33"),
                            Category = 4,
                            ExerciseName = "45 Minute HIIT Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("5464d40f-f0e1-48d7-9c5d-f827a234577d"),
                            Category = 3,
                            ExerciseName = "Beginner Strength Training Workout",
                            ExpertiseLevel = 1
                        },
                        new
                        {
                            Id = new Guid("f393a1d9-e856-4e38-8138-2c00e26204b1"),
                            Category = 1,
                            ExerciseName = "Intermediate Fat Loss Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("5a6f1b96-fcec-4551-a17f-b11c2c327ae8"),
                            Category = 1,
                            ExerciseName = "Intermediate Fat Loss Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("1b08f335-4c23-49e6-b9d1-2bfa9cdd1157"),
                            Category = 4,
                            ExerciseName = "Intermediate Fat Loss Workout",
                            ExpertiseLevel = 2
                        },
                        new
                        {
                            Id = new Guid("9d23751c-5c98-4608-9681-9bbfca61251e"),
                            Category = 4,
                            ExerciseName = "Intermediate Fat Loss Workout",
                            ExpertiseLevel = 3
                        },
                        new
                        {
                            Id = new Guid("45632520-a6fa-480f-9fba-ae342e4a1706"),
                            Category = 1,
                            ExerciseName = "Beginner At Home Workout",
                            ExpertiseLevel = 1
                        });
                });

            modelBuilder.Entity("FitByBitService.Entities.Models.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Calories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("142dfe66-637d-4a59-a60f-bd2694ae670c"),
                            Calories = "130",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2442),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2445),
                            Name = "White Rice"
                        },
                        new
                        {
                            Id = new Guid("3bd92e02-ef78-4ce2-a427-65cca332329a"),
                            Calories = "130",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2476),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2476),
                            Name = "Medium Grain White Rice"
                        },
                        new
                        {
                            Id = new Guid("b62aac6f-5c51-4611-99a0-124b09e0e4ab"),
                            Calories = "108",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2479),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2479),
                            Name = "Rice Noodles (Cooked)"
                        },
                        new
                        {
                            Id = new Guid("fdf77f82-2d8d-4e4f-bc58-012634d1590f"),
                            Calories = "123",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2481),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2481),
                            Name = "Brown Rice"
                        },
                        new
                        {
                            Id = new Guid("f50008ac-4888-4e24-a12e-8820bc4ba85f"),
                            Calories = "145",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2483),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2483),
                            Name = "Beef And Rice No Sauce"
                        },
                        new
                        {
                            Id = new Guid("acbd9e99-c67e-44bf-a3cd-0897bd1faabd"),
                            Calories = "136",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2487),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2487),
                            Name = "Beef And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("9a9f40c1-15f1-4dcb-bd71-2752ce52efd7"),
                            Calories = "112",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2489),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2489),
                            Name = "Chili Con Carne With Beans And Rice"
                        },
                        new
                        {
                            Id = new Guid("06f5a277-8602-494d-8df8-d2acaf8741c5"),
                            Calories = "139",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2504),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2505),
                            Name = "Pork And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("d77af16b-01ca-427b-97a2-960b3afbd326"),
                            Calories = "148",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2507),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2507),
                            Name = "Chicken Or Turkey And Rice No Sauce"
                        },
                        new
                        {
                            Id = new Guid("a3eec80f-d569-4e23-b0aa-2b274cec338b"),
                            Calories = "141",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2510),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2511),
                            Name = "Chicken Or Turkey And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("3848087d-1161-4870-b09a-4250c001417a"),
                            Calories = "135",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2512),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2513),
                            Name = "Fish And Rice With Tomato-Based Sauce"
                        },
                        new
                        {
                            Id = new Guid("4542c9c9-de32-480b-a09e-e1fe342d4eab"),
                            Calories = "147",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2514),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2515),
                            Name = "Beef, Rice And Vegetables"
                        },
                        new
                        {
                            Id = new Guid("a79c1eb4-b770-46c0-9e67-2b615ba50005"),
                            Calories = "128",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2516),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2516),
                            Name = "Pork, Rice And Vegetables "
                        },
                        new
                        {
                            Id = new Guid("9694908a-ef55-41a9-bee7-254077ae1034"),
                            Calories = "381",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2518),
                            FoodGroup = "3",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2518),
                            Name = "Cereal (Kellogg's Rice Krispies)"
                        },
                        new
                        {
                            Id = new Guid("1da4bb91-9df8-4b4b-aae5-60c87d1bc30c"),
                            Calories = "149",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2520),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2520),
                            Name = "Whole Wheat Pasta"
                        },
                        new
                        {
                            Id = new Guid("f476d60a-250d-4493-b6ed-af4cbddaceed"),
                            Calories = "157",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2525),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2525),
                            Name = "Pasta Cooked"
                        },
                        new
                        {
                            Id = new Guid("b5377e48-74b2-443a-b23b-d4ee393b6d65"),
                            Calories = "148",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2527),
                            FoodGroup = "1",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2527),
                            Name = "Pasta Whole Grain Cooked"
                        },
                        new
                        {
                            Id = new Guid("76441fc3-eadb-4752-ad26-164fad96d6ae"),
                            Calories = "192",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2530),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2530),
                            Name = "Chicken Breast Baked"
                        },
                        new
                        {
                            Id = new Guid("ea0fcf1a-d8a2-4ecb-9617-a740db303a24"),
                            Calories = "176",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2532),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2532),
                            Name = "Chicken Breast Grilled"
                        },
                        new
                        {
                            Id = new Guid("226b6c97-2a24-41f1-b0aa-8fec059cbbe8"),
                            Calories = "226",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2534),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2534),
                            Name = "Chicken Leg Drumstick And Thigh Baked"
                        },
                        new
                        {
                            Id = new Guid("f9d4244c-cb52-428f-a713-67aa7cc113fd"),
                            Calories = "190",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2536),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2536),
                            Name = "Chicken Drumstick Baked"
                        },
                        new
                        {
                            Id = new Guid("e9386ea7-70f2-462e-8c3d-214275dfd4b4"),
                            Calories = "200",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2538),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2538),
                            Name = "Chicken Drumstick Grilled"
                        },
                        new
                        {
                            Id = new Guid("c29c1ab0-6c3c-4959-973d-effaf0d432c0"),
                            Calories = "211",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2539),
                            FoodGroup = "2",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2540),
                            Name = "Chicken Drumstick Fried"
                        },
                        new
                        {
                            Id = new Guid("ec3f5900-7653-4858-b964-413121dcbe05"),
                            Calories = "182",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2544),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2545),
                            Name = "Wild Atlantic Salmon"
                        },
                        new
                        {
                            Id = new Guid("7f51c0f0-7e6c-4ade-9436-65246993f5b1"),
                            Calories = "117",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2546),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2547),
                            Name = "Smoked Salmon"
                        },
                        new
                        {
                            Id = new Guid("5d3b3b31-d49d-4f45-a536-7ea129af3e23"),
                            Calories = "167",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2548),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2549),
                            Name = "Canned Salmon"
                        },
                        new
                        {
                            Id = new Guid("16ca550c-3411-432c-b799-59f48fbbf6d4"),
                            Calories = "136",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2550),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2551),
                            Name = "Canned Pink Salmon"
                        },
                        new
                        {
                            Id = new Guid("b2f083a9-1f51-4edf-a13e-a728fcb8aca5"),
                            Calories = "206",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2552),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2552),
                            Name = "Farmed Atlantic Salmon"
                        },
                        new
                        {
                            Id = new Guid("0208e491-23e5-410b-bdf1-535cc440664e"),
                            Calories = "183",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2614),
                            FoodGroup = "4",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2614),
                            Name = "Salmon Baked"
                        },
                        new
                        {
                            Id = new Guid("687a5531-a4df-4840-844b-9ad6eaad994e"),
                            Calories = "71",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2617),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2617),
                            Name = "Fortified Fruit Juice Smoothie"
                        },
                        new
                        {
                            Id = new Guid("cd9c1722-bc72-4770-b35b-6f4dc562c927"),
                            Calories = "52",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2619),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2619),
                            Name = "Apples"
                        },
                        new
                        {
                            Id = new Guid("6a4873eb-d8f4-44f4-be3e-8c3bbee87b4f"),
                            Calories = "48",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2624),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2624),
                            Name = "Apples (Without Skin)"
                        },
                        new
                        {
                            Id = new Guid("85b19459-490b-427a-8066-190fa9677902"),
                            Calories = "89",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2626),
                            FoodGroup = "5",
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2626),
                            Name = "Bananas"
                        });
                });

            modelBuilder.Entity("FitByBitService.Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("Bmi")
                        .HasColumnType("float");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentFitness")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FitnessGoal")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StartingWeight")
                        .HasColumnType("float");

                    b.Property<double>("TargetWeight")
                        .HasColumnType("float");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "adecb697-fa5f-4625-bc49-5d45265de74d",
                            AccessFailedCount = 0,
                            Age = 23,
                            Bmi = 1.8899999999999999,
                            ConcurrencyStamp = "40da3646-e596-45b6-8275-f7e1ff6eca79",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2775),
                            CurrentFitness = 1,
                            Email = "superuserD@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            FitnessGoal = 1,
                            Height = 1.8300000000000001,
                            IsActive = true,
                            IsDeleted = false,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2775),
                            NormalizedEmail = "SUPERUSERD@GMAIL.COM",
                            NormalizedUserName = "SUPERUSER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJkXs+pAs3yQz99TcaMmI0xQUTvdv8ZVVDBygGS/ehHwOgoQpZyO3v+9mBvE8JmIcA==",
                            PhoneNumber = "08130927418",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "eaa96e01-9cb8-43d4-a27c-d0074134645e",
                            StartingWeight = 80.0,
                            TargetWeight = 0.0,
                            TwoFactorEnabled = false,
                            UserName = "superuser@gmail.com"
                        },
                        new
                        {
                            Id = "e4d269e5-7dc3-4a65-9485-578156f0e746",
                            AccessFailedCount = 0,
                            Age = 23,
                            Bmi = 1.8899999999999999,
                            ConcurrencyStamp = "0561bc76-f79d-400d-a3dd-256a685c73a3",
                            CreatedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2829),
                            CurrentFitness = 1,
                            Email = "osinfadeidris@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Idris",
                            FitnessGoal = 1,
                            Height = 1.8300000000000001,
                            IsActive = true,
                            IsDeleted = false,
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Osinfade",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 4, 21, 10, 33, 38, 43, DateTimeKind.Utc).AddTicks(2829),
                            NormalizedEmail = "OSINFADEIDRIS@GMAIL.COM",
                            NormalizedUserName = "OSINFADEIDRIS@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJkXs+pAs3yQz99TcaMmI0xQUTvdv8ZVVDBygGS/ehHwOgoQpZyO3v+9mBvE8JmIcA==",
                            PhoneNumber = "07069576909",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "6a09160e-9efb-4da9-bffe-e18debfaba2f",
                            StartingWeight = 80.0,
                            TargetWeight = 0.0,
                            TwoFactorEnabled = false,
                            UserName = "osinfadeidris@gmail.com"
                        });
                });

            modelBuilder.Entity("FitByBitService.Entities.Models.VerificationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("Expiry")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VerificationOtps");
                });

            modelBuilder.Entity("FitByBitService.Entities.Models.VerificationOtp", b =>
                {
                    b.HasOne("FitByBitService.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
